# Generated by Django 3.0.6 on 2020-05-23 14:34

from django.db import migrations, models
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=20, null=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_code', models.CharField(max_length=20)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('tags', models.ManyToManyField(blank=True, to='videos.Tag')),
            ],
        ),
    ]
