# Generated by Django 3.0.6 on 2020-06-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['publish_date']},
        ),
    ]
