# Generated by Django 3.0.6 on 2020-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200601_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, null=True),
        ),
    ]
