# Generated by Django 3.0.6 on 2020-06-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200604_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-publish_date']},
        ),
    ]
