# Generated by Django 3.1.2 on 2020-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200604_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/videos/'),
        ),
    ]
