# Generated by Django 3.0.6 on 2020-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200601_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='init_password',
            field=models.CharField(default='DuzRJ63v', max_length=10),
        ),
    ]
