# Generated by Django 3.0.6 on 2020-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200601_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='init_password',
            field=models.CharField(default='RqHVkQdA', max_length=10),
        ),
    ]
