# Generated by Django 3.0.6 on 2020-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('users', '0006_auto_20200601_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_file',
            field=models.ManyToManyField(to='files.File'),
        ),
    ]
