# Generated by Django 3.0.6 on 2020-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_available_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recurrrecurring_payments',
            field=models.BooleanField(default=False),
        ),
    ]
