# Generated by Django 3.0.6 on 2020-09-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_recurrrecurring_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recurrrecurring_payments',
            new_name='recurring_payments',
        ),
    ]
