# Generated by Django 3.1.2 on 2020-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201002_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='user',
            name='refund',
            field=models.CharField(blank=True, choices=[('Card', 'Возврат на карту'), ('Charity', 'Перевод на благотворительность')], max_length=10, null=True, verbose_name='Вариант возврата'),
        ),
    ]
