# Generated by Django 3.1.2 on 2020-11-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201129_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='refund',
            new_name='refund_choice',
        ),
    ]
