# Generated by Django 3.0.6 on 2020-05-23 14:35

from django.db import migrations, models


def load_fixtures(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'email.json')
    call_command('loaddata', 'price.json')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('is_html', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('template_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('number_of_months', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RunPython(load_fixtures)
    ]
