# Generated by Django 3.0.6 on 2020-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='number_of_months',
            field=models.IntegerField(unique=True),
        ),
    ]
