# Generated by Django 3.0.6 on 2020-06-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200605_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['number_of_months']},
        ),
    ]
