# Generated by Django 3.0.6 on 2020-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
