# Generated by Django 3.1.2 on 2020-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20200902_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
