# Generated by Django 3.1.2 on 2020-10-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
