# Generated by Django 3.1.2 on 2020-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20201005_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='number_of_months',
            field=models.IntegerField(),
        ),
    ]
