# Generated by Django 3.0.5 on 2020-04-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('subscribe_until', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['subscribe_until'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=0, max_length=10)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(default=0, max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='followers.User')),
            ],
        ),
    ]
