# Generated by Django 3.0.6 on 2020-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
