# Generated by Django 3.0.6 on 2020-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200604_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='available_to_active_subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
