# Generated by Django 3.0.6 on 2020-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_recurrentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrentpayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
